<MyScreenManager>:
    HomeScreen:
    CalcScreen:
    AboutScreen:

<HomeScreen>:
    name: "home"
    BoxLayout:
        orientation: "vertical"
        spacing: 20
        padding: 30

        Image:
            source: "logo.png"

        Label:
            text: "My Smart App"
            font_size: "32sp"

        Button:
            text: "🧮 الآلة الحاسبة"
            on_press: root.manager.current = "calc"

        Button:
            text: "ℹ️ عن التطبيق"
            on_press: root.manager.current = "about"

        Button:
            text: "❌ خروج"
            on_press: app.stop()

<AboutScreen>:
    name: "about"
    BoxLayout:
        orientation: "vertical"
        padding: 30
        spacing: 20

        Label:
            text: "تطبيق تجريبي معمول ببايثون و Kivy"

        Button:
            text: "⬅ رجوع"
            on_press: root.manager.current = "home"

<CalcScreen>:
    name: "calc"
    BoxLayout:
        orientation: "vertical"
        padding: 20
        spacing: 10

        Label:
            text: root.result
            font_size: "32sp"
            size_hint_y: 0.2

        GridLayout:
            cols: 4
            spacing: 10

            Button: text: "7"; on_press: root.add("7")
            Button: text: "8"; on_press: root.add("8")
            Button: text: "9"; on_press: root.add("9")
            Button: text: "/"; on_press: root.add("/")

            Button: text: "4"; on_press: root.add("4")
            Button: text: "5"; on_press: root.add("5")
            Button: text: "6"; on_press: root.add("6")
            Button: text: "*"; on_press: root.add("*")

            Button: text: "1"; on_press: root.add("1")
            Button: text: "2"; on_press: root.add("2")
            Button: text: "3"; on_press: root.add("3")
            Button: text: "-"; on_press: root.add("-")

            Button: text: "0"; on_press: root.add("0")
            Button: text: "C"; on_press: root.clear()
            Button: text: "="; on_press: root.calculate()
            Button: text: "+"; on_press: root.add("+")

        Button:
            text: "⬅ رجوع"
            size_hint_y: 0.15
            on_press: root.manager.current = "home"
